In [3]:
import numpy as np

In [2]:
# Rows: Donators (Donator1, Donator2, Donator3, Donator4)
# Columns: Months (January, February, March)
donations = np.array([
    [10, 15, 20],   # Donator1
    [5,  7,  9],    # Donator2
    [12, 14, 16],   # Donator3
    [20, 25, 30]    # Donator4
])


# Question
1. Calculate the total donation made by each donator.

2. Find the total donations received in each month.

3. Determine the average donation per donator.

4. Identify the donator who contributed the most in March.

5. Compute the percentage of total donations each donator made.

6. Apply a 5% increase in all donations and get the updated dataset.

7. Find months where Donator3 donated more than ₹13,000.

8. Normalize the donation data per donator using min-max scaling.

In [9]:
sum_donator = np.sum(donations[:],axis=1)
print("total donation made by each donator : " , sum_donator)

total donation made by each donator :  [45 21 42 75]


In [12]:
sum_month = np.sum(donations[:],axis=0)
print("total donations received in each month: " , sum_month)

total donations received in each month:  [47 61 75]


In [14]:
avg_donator = np.mean(donations[:],axis=1)
print("average donation per donator: " , avg_donator)

average donation per donator:  [15.  7. 14. 25.]


In [16]:
max_march = np.max(donations[:,2],axis=0)
print("donator who contributed the most in March:" , max_march)

donator who contributed the most in March: 30


In [19]:
sum_donations = np.sum(donations[:],axis=1)
sum_overall = np.sum(sum_donations)
percentage = (sum_donations / sum_overall) * 100
print("percentage of total donations each donator made: " , percentage)

percentage of total donations each donator made:  [24.59016393 11.47540984 22.95081967 40.98360656]


In [21]:
increase_donations = donations * 1.05
print("5% increase in all donations and get the updated dataset:\n" , increase_donations)

5% increase in all donations and get the updated dataset:
 [[10.5  15.75 21.  ]
 [ 5.25  7.35  9.45]
 [12.6  14.7  16.8 ]
 [21.   26.25 31.5 ]]


In [28]:
donator3 = donations[2]
print(donator3)
months = np.where(donator3 > 13)[0]
print("Donator3 donated more than ₹13,000 in month indices:", months)

[12 14 16]
Donator3 donated more than ₹13,000 in month indices: [1 2]


In [38]:
# normalize formula
# normalize_donation = (value - min) / (min - max)

normalized_donations = (donations - donations.min(axis=1)[:, None]) / (donations.max(axis=1) - donations.min(axis=1))[:, None]
print("Normalize the donation data per donator using min-max scaling:\n" , normalized_donations)

Normalize the donation data per donator using min-max scaling:
 [[0.  0.5 1. ]
 [0.  0.5 1. ]
 [0.  0.5 1. ]
 [0.  0.5 1. ]]


# Hotel Dataset
# Hotel	  Rating 	Rooms	Price per Night ($)
# HotelA   4.2	    120	    150
# HotelB   3.5	    200	    100
# HotelC   4.7	    80	    250
# HotelD   3.9	    150	    180
# HotelE   4.0	    90	    220



# NumPy Questions for AI/ML Skills
1. Array Basics
Create a NumPy array for hotel data.

2. What is the shape and data type of the array? dtype

# 2. Indexing & Slicing
3. Retrieve the ratings of all hotels.

4. Get the number of rooms in the third hotel.

5. Extract only the price column.

# 3. Conditional Filtering
6. Find hotels with ratings above 4.0.

7. How many hotels have more than 100 rooms?

8. Get the prices of hotels where rating < 4.0.

# 4. Math Operations
9. What is the average price of all hotels?

10. Find the total number of rooms available.

11. Compute the difference between highest and lowest rating.

# 5. Aggregation (with axis)
12. Calculate the average rating, rooms, and price across all hotels.

13. Find the max value for each column.

14. Find the sum of ratings for each hotel (row-wise sum).

# 6. Normalization & Scaling
15. Normalize the price column using min-max scaling.

16. Normalize the full dataset column-wise.

# 7. Dot Product (optional)
17. Multiply each hotel’s data by a weight vector: [0.3, 0.1, 0.6] using np.dot.
                       

In [5]:
# 1 question .

# [Rating, Rooms, Price]
hotel_data = np.array([
    [4.2, 120, 150],  # Hotel A
    [3.5, 200, 100],  # Hotel B
    [4.7, 80, 250],   # Hotel C
    [3.9, 150, 180],  # Hotel D
    [4.0, 90, 220]    # Hotel E
])
print(hotel_data)
print("shape of the data type are : " , np.shape(hotel_data))
print("Data type of an array : " , hotel_data.dtype)

[[  4.2 120.  150. ]
 [  3.5 200.  100. ]
 [  4.7  80.  250. ]
 [  3.9 150.  180. ]
 [  4.   90.  220. ]]
shape of the data type are :  (5, 3)
Data type of an array :  float64


In [33]:
# 2. questions

print("Rating columns : " , hotel_data[:,0])
print("number of rooms in third hotel : " , hotel_data[2,1])
print("Price columns : " , hotel_data[:,2])

Rating columns :  [4.2 3.5 4.7 3.9 4. ]
number of rooms in third hotel :  80.0
Price columns :  [150. 100. 250. 180. 220.]


In [34]:
# 3. questions

print("hotels with ratings above 4.0 :\n " , hotel_data[hotel_data[:,0] > 4.0])
print("Find the total number of rooms available:",np.sum(hotel_data[:,1]))
print("The prices of hotels where rating < 4.0:",hotel_data[hotel_data[:,0] < 4.0,2])



hotels with ratings above 4.0 :
  [[  4.2 120.  150. ]
 [  4.7  80.  250. ]]
Find the total number of rooms available: 640.0
The prices of hotels where rating < 4.0: [100. 180.]


In [37]:
# 4. questions

print("The average price of all hotels:",np.mean(hotel_data[:,2]))
print("the total number of rooms available : ", np.sum(hotel_data[:,1]))
print("The difference between highest and lowest rating:",np.max(hotel_data[:,0]) - np.min(hotel_data[:,0]))

The average price of all hotels: 180.0
the total number of rooms available :  640.0
The difference between highest and lowest rating: 1.2000000000000002


In [6]:
# 5. question
print("Average (rating, rooms, price) per hotel:", np.mean(hotel_data, axis=1))
print("Maximum (rating, rooms, price) across all hotels:", np.max(hotel_data, axis=0))
print("Total sum of ratings across all hotels:", np.sum(hotel_data[:, 0]))

Average (rating, rooms, price) per hotel: [ 91.4        101.16666667 111.56666667 111.3        104.66666667]
Maximum (rating, rooms, price) across all hotels: [  4.7 200.  250. ]
Total sum of ratings across all hotels: 20.3


In [8]:
# 6. question
price_column = hotel_data[:, 2]
min_price = np.min(price_column)
max_price = np.max(price_column)
normalized_price = (price_column - min_price) / (max_price - min_price)

print("Normalized price column: \n ", normalized_price)

min_vals = np.min(hotel_data, axis=0)
max_vals = np.max(hotel_data, axis=0)
normalized_data = (hotel_data - min_vals) / (max_vals - min_vals)

print("Normalized hotel data (column-wise):\n", normalized_data)

Normalized price column: 
  [0.33333333 0.         1.         0.53333333 0.8       ]
Normalized hotel data (column-wise):
 [[0.58333333 0.33333333 0.33333333]
 [0.         1.         0.        ]
 [1.         0.         1.        ]
 [0.33333333 0.58333333 0.53333333]
 [0.41666667 0.08333333 0.8       ]]


In [9]:
# 7. question

weights = np.array([0.3, 0.1, 0.6])
weighted_scores = np.dot(hotel_data, weights)
print("Weighted scores for each hotel:\n", weighted_scores)

Weighted scores for each hotel:
 [103.26  81.05 159.41 124.17 142.2 ]
